services:
  app:
    build:
      context: .
      args:
        user: laravel
        uid: 1000
    image: kpum-app
    container_name: kpum-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - kpum-network

  pro-worker:
    build:
      context: .
      args:
        user: laravel
        uid: 1000
    image: kpum-worker
    container_name: kpum-worker
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=90
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - app
      - db
      - redis
    networks:
      - kpum-network

  nginx:
    image: nginx:alpine
    container_name: kpum-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - kpum-network

  db:
    image: mysql:8.0
    container_name: kpum-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-kpum}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - kpum-network

  redis:
    image: redis:alpine
    container_name: kpum-redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - kpum-network

networks:
  kpum-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
