services:
  app:
    build:
      context: .
      network: host
      args:
        user: laravel
        uid: 1000
    image: kpum-app
    container_name: kpum-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/zzz-docker-fpm-tuning.conf:/usr/local/etc/php-fpm.d/zzz-docker-fpm-tuning.conf
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - kpum-network

  pro-worker:
    build:
      context: .
      network: host
      args:
        user: laravel
        uid: 1000
    image: kpum-app # Use same image
    restart: unless-stopped
    command: php artisan queue:work --queue=high --tries=3 --timeout=600 --sleep=1
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 4096M
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - app
      - db
      - redis
    networks:
      - kpum-network

  default-worker:
    build:
      context: .
      network: host
      args:
        user: laravel
        uid: 1000
    image: kpum-app
    container_name: kpum-default-worker
    restart: unless-stopped
    command: php artisan queue:work --queue=default --tries=1 --timeout=1800
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - app
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 4096M
    networks:
      - kpum-network

  nginx:
    image: nginx:alpine
    container_name: kpum-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - kpum-network

  db:
    image: mysql:8.0
    container_name: kpum-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-kpum}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-root}"]
      retries: 3
      timeout: 5s
    networks:
      - kpum-network

  redis:
    image: redis:alpine
    container_name: kpum-redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - kpum-network

networks:
  kpum-network:
    driver: bridge

volumes:
  dbdata:
  redisdata:
